//
//  Copyright (C) Ricardo Ruiz López, 2010. All rights reserved.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

#import <UIKit/UIKit.h>

typedef enum {
	RETRIEVING_DATA,
	ERROR_RETRIEVING_DATA,
	DATA_WAS_RETRIEVED_CORRECTLY
} DataModelState;

@interface GlobalHighscoresViewController : UITableViewController {
	NSArray* m_highscores;
	DataModelState m_modelDataState;
	NSInteger m_errorCode;
}
@property (nonatomic,retain) NSArray* m_highscores;
-(void) loadHighscores;
@end
